### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by nima-hakimi** [navikt/delta-backend#19]
Det står feil java versjon i readme. Java version er 21 :)

**Comment by eilifjohansen** [comment]
Oppdatert!

Godt poeng med java 21, slet litt med å få backenden til å fungere lokalt i forrige uke. Tok litt tid før jeg forsto at jeg måtte inn på Gradle instillingene i intellij, der er det en dropdown meny Gradle JVM, der man kan laste ned og endre til java versjon 21 for å få appen til å kjøre.
